#!/usr/bin/python3

import sqlite3,sys

if len(sys.argv) != 2:
  print("Usage:",sys.argv[0],"title keyword")
  sys.exit(1)

keyWord = sys.argv[1]

con = sqlite3.connect('a2.db')

cur = con.cursor()

query = "SELECT mov.title, mov.year, mov.content_rating, rat.imdb_score, gen.genre " \
        "FROM movie mov " \
        "INNER JOIN rating rat on rat.movie_id=mov.id " \
        "INNER JOIN genre gen on gen.movie_id=mov.id " \
        "WHERE mov.title LIKE '%{}%' " \
        "ORDER BY mov.year ASC, rat.imdb_score DESC, mov.title ASC, gen.genre ASC"

cur.execute(query.format(keyWord))
num = 1
noneYearMovieList = []
while True:
  t = cur.fetchone()
  if t == None:
    break
  movTitle, movYear, movCon, movRat, movGen = t
  if movYear != None:
    prevMovTitile = movTitle
    if movCon != None:
      print('{}. {} ({}, {}, {:.1f}) [{}'.format(num, movTitle, movYear, movCon, movRat, movGen), end='')
    elif movCon == None:
      print('{}. {} ({}, {:.1f}) [{}'.format(num, movTitle, movYear, movRat, movGen), end='')
    while True:
      t = cur.fetchone()
      if t == None:
        print(']')
        break
      movTitle, movYear, movCon, movRat, movGen = t
      if movTitle == prevMovTitile:
        print(',{}'.format(movGen), end='')
      elif movTitle != prevMovTitile:
        print(']')
        num += 1
        if movCon != None:
          print('{}. {} ({}, {}, {:.1f}) [{}'.format(num, movTitle, movYear, movCon, movRat, movGen), end='')
        elif movCon == None:
          print('{}. {} ({}, {:.1f}) [{}'.format(num, movTitle, movYear, movRat, movGen), end='')
        prevMovTitile = movTitle
  elif movYear == None:
    noneYearMovieList.append(t[0::])

i = 0
j = 0
listLen = len(noneYearMovieList)
while i < listLen:
  num += 1
  count = 0
  movTitle, movYear, movCon, movRat, movGen = noneYearMovieList[i]
  if movCon != None:
    print('{}. {} ({}, {:.1f}) [{}'.format(num, movTitle, movCon, movRat, movGen), end='')
  elif movCon == None:
    print('{}. {} ({:.1f}) [{}'.format(num, movTitle, movRat, movGen), end='')
  prevMovTitile = movTitle
  j = i + 1
  while j < listLen:
    movTitle, movYear, movCon, movRat, movGen = noneYearMovieList[j]
    if movTitle == prevMovTitile:
      print(',{}'.format(movGen), end='')
      count += 1
    j += 1
  print(']')
  i += count + 1  
